-- Script FPE. #1
loadstring(game:HttpGet("https://raw.githubusercontent.com/Clair3169/FPE-S-script/refs/heads/main/FPE%3As_esp_script.lua", true))()

-- TextLabel #2
loadstring(game:HttpGet("https://raw.githubusercontent.com/Clair3169/FPE-S-script/refs/heads/main/TextLabel.lua", true))()

-- JumpPower Perma #3
loadstring(game:HttpGet("https://raw.githubusercontent.com/Clair3169/FPE-S-script/refs/heads/main/JumpPower_Perma.lua", true))()

-- loadstring(game:HttpGet("URL_AQUI", true))()
